package me.limeglass.skungee.objects;

public enum BungeePacketType {
	PINGSERVER,
	PLAYERDISCONNECT,
	PLAYERCHAT,
	PLAYERLOGIN,
	EVALUATE,
	GLOBALSCRIPTS,
	UPDATEVARIABLES,
	PLAYERSWITCH,
	PLAYERCOMMAND;
}
