package me.limeglass.skungee.common.packets;

public enum ProxyPacketType {
	PINGSERVER,
	PLAYERDISCONNECT,
	PLAYERCHAT,
	PLAYERLOGIN,
	EVALUATE,
	GLOBALSCRIPTS,
	UPDATEVARIABLES,
	PLAYERSWITCH,
	PLAYERCOMMAND,
	SHUTDOWN,
	SERVERLISTPING,
	SKUNGEEMESSAGES,
	DISCONNECT,
	CUSTOM;
}
